var GAME_LEVELS = [
  ["                                        ",
   "                                        ",
   "     y                y                 ",
   "                            y           ",
   "          y                             ",
   "                                        ",
   "                  y                     ",
   "                                 *      ",
   "  @                                     ",
   "       ! !      o       g     s         ",
   " zxxxxxxxxxxc zxxxxxxxxxxxc zxxxxxxxxxxc",
   "                                        ",
   "                                 y      ",
   "         y                              ",
   "                                        ",
   "                     y                  ",
   "                                        ",
   "                                        ",
   "                                        "],
  ["                                                      *                         ",
   "                                                                                ",
   "                                                                                ",
   "                           y                       zxxxxxxc                     ",
   "                                                 zc                             ",
   "        y                                    ! zc                               ",
   "                                            zxc                                 ",
   "                                        zc                             y        ",
   "                        y           o                 y                         ",
   "                                        g                                       ",
   "                                   zxxc                                         ",
   "          g     y                     zc                        y               ",
   "                        g                      g                                ",
   "                                          zxc                                   ",
   "   y                                                                            ",
   "                        o       zxc               zc                            ",
   "     @                                                                          ",
   "                                       ! ! !                                    ",
   "  zxxxc zxxxxxc  o  = zxxc            zxxxxxc        zxc                y       ",
   "               zxxxxxc          !                                               ",
   "                              zxxxc                   o    !                    ",
   "                                                    zxxxxxxxc         s         ",
   "           y                                                  zc  =       =  zxc",
   "                                                                zxxxxxxxxxxxc   "],

  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                             y                    ",
   "                                                                        y                                         ",
   "                                                                                                                  ",
   "                                             y                                                                    ",
   "                                                                                                                  ",
   "                 y                                                                    y                           ",
   "                                                           y                                                      ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                zc g zxxxxxc      zxxxxxc         ",
   "                                                                              zc                                  ",
   "                                y                                           zc                                    ",
   "                                                           o              zc                 o                    ",
   "                                                                        zc                                        ",
   "                                                       g zxxc  g  zxxc                     g    o g               ",
   "                                                 zxxc                                                             ",
   "            zxxxxxxc zxxxxxxc                 g         y                        y          g    g                ",
   "    @    g           y                zxxxc zxc                                            g  o   g               ",
   "                                                ! ! ! ! ! ! ! ! ! ! !                          y                  ",
   "  zxxxxxxxc   =  o  =  o =    zxxxc g         zxxxxxxxxxxxxxxxxxxxxxxc                                            ",
   "           zxxxxxxxxxxxxxxxxxc    ! ! ! ! !                                                  ! o !                ",
   "                                 zxxxxxxxxxxc                                        zc =   zxc zxc  =  zc        ",
   "                            y                                 g    g    g   g         zxxxxxxc   zxxxxxc          ",
   "                                                 y                                                                ",
   "            y                                                                                  s             y    ",
   "                                 *                                           y                zxc                 ",
   "                                                                                                         !        ",
   "                        o  ! !           !        !       zxc  zxc  zxc  zxc  zxxxc       zxc           zxc   zxc ",
   "                       zxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxc                             !                             ",
   "                                                                                   zxxc                           ",
   "                                                                                                                  "],

  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                         y                                    ",
   "                                                                                                              ",
   "                                                                                       y                      ",
   "                       y                                                                                      ",
   "                                                                                                              ",
   "                                                      y                                                       ",
   "       y                                                                                                      ",
   "                                                                                                              ",
   "                                                                                            y                 ",
   "                                                                                                              ",
   "                                                                                                              ",
   "       zxxxxc              g                           g                y                                     ",
   "     zc      zc                          o                                                                    ",
   "   zc     y    zc                                                                                             ",
   " zc                                     zxc                                                                   ",
   "zc      !                                      y                                            !                 ",
   "  zxc zxxxxxxxxc zc zc =    =   =  y =      =   =    = =  =   zc  zc                     zxxxxxc              ",
   "   zc!   s      !!!!! zxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxc    !!  zc      g        zc             ! !  ",
   "    zxc  o     zxxxxxc                                              zxxc   zc       y     zc         zxxxxxxc ",
   "      zc      zc                      y                                  zc !  !  ! zc                        ",
   "        zc  zc                                                             zxxxxxxxc           =    zc        ",
   "      zc                                          y                                       zxxxxxxxc           ",
   "        zxxc     zxc       zc                                   y                    g                        ",
   "            zxc       zc                                                             g                        ",
   "                             zxxc                                    o               g                        ",
   "                g                 zxc   !    =     =    =   !                                                 ",
   "                          g            zxxxxxxxxxxxxxxxxxxxxxc zxc   !   zxc     zxc   zxc                    ",
   "           ! ! ! ! ! ! ! ! ! ! !                                    zxc              !                        ",
   "         zxxxxxxxxxxxxxxxxxxxxxxc !                                                 zxc                       ",
   "                                 zxc    zxxxxxxc                              g                               ",
   "                                    zxc            !  @                                                       ",
   "                                     o           zxxxxxc                                                      ",
   "                                    zxc                                                                       ",
   "                                  g                     zc                                                    ",
   "                                    zxc                                                                       ",
   "                                  g  o                     zc                        o                        ",
   "                                    zxc                                             ooo                       ",
   "     *                                                        zc                   ooooo                      ",
   "                                    zxxxxc                        zc              ooooooo                     ",
   "                     !   !   !                                        zxxc       ooooooooo                    ",
   "  zxxxxxxxxxc     zxxxxxxxxxxxxxxc                                           zxxxxxxxxxxxxxxxxc               ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "],

   ["                                                              ",
    "                                                              ",
    "             o   o  o   ooo  ooo  oooo  ooo  o  o             ",
    "              o o   o  o      o   o  o  ooo   oo              ",
    "               o    o   ooo   o   oooo  o  o  o               ",
    "                                                              ",
    "                                                              ",
    "                                                              ",
    "                                                              ",
    "                                                              ",
    "                        @                                     ",
    "   zxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxc   ",
    "                                                              ",
    "                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
